/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lzy01_imagecut_opencv_JniFunction */

#ifndef _Included_com_example_lzy01_imagecut_opencv_JniFunction
#define _Included_com_example_lzy01_imagecut_opencv_JniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lzy01_imagecut_opencv_JniFunction
 * Method:    DoCanny
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_lzy01_imagecut_1opencv_JniFunction_DoCanny
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_lzy01_imagecut_opencv_JniFunction
 * Method:    DoGrabCut
 * Signature: (Ljava/lang/Object;[I)V
 */
JNIEXPORT void JNICALL Java_com_example_lzy01_imagecut_1opencv_JniFunction_DoGrabCut
  (JNIEnv *, jclass, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
